import { useEffect, useState } from "react";
import { fetchCycleNarrative, type CycleAnalysis } from "@/api/endpoints/marketData";

interface Props {
    cycleData: CycleAnalysis;
}

export function AINarrative({ cycleData }: Props) {
    const [narrative, setNarrative] = useState<string | null>(null);
    const [loading, setLoading] = useState(true);
    const [notConfigured, setNotConfigured] = useState(false);
    const [error, setError] = useState(false);

    // Re-fetch narrative whenever the upstream data's timestamp changes.
    const stamp = cycleData.lastUpdated;
    useEffect(() => {
        let cancelled = false;
        setLoading(true);
        setError(false);
        fetchCycleNarrative(cycleData)
            .then((res) => {
                if (cancelled) return;
                if (res.data.error === "not configured") {
                    setNotConfigured(true);
                    setNarrative(null);
                } else if (res.data.narrative) {
                    setNarrative(res.data.narrative);
                    setNotConfigured(false);
                } else {
                    setError(true);
                }
            })
            .catch(() => { if (!cancelled) setError(true); })
            .finally(() => { if (!cancelled) setLoading(false); });
        return () => { cancelled = true; };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [stamp]);

    return (
        <div style={{
            borderLeft: "3px solid #F59E0B", background: "rgba(245,158,11,0.05)",
            padding: "16px 20px", marginTop: 20,
            fontFamily: "'Space Mono', monospace", color: "#FEF3C7",
        }}>
            <div style={{
                fontSize: 9, letterSpacing: 3, color: "#F59E0B",
                marginBottom: 10, display: "flex", alignItems: "center", gap: 8,
            }}>
                <span>⚡ AI ANALYSIS — GENERATED BY CLAUDE</span>
            </div>

            {loading && (
                <div style={{ color: "rgba(254,243,199,0.4)", fontSize: 11, letterSpacing: 1 }}>
                    Generating narrative...
                </div>
            )}

            {!loading && notConfigured && (
                <div style={{ color: "rgba(254,243,199,0.35)", fontSize: 11, letterSpacing: 1 }}>
                    AI narrative unavailable (ANTHROPIC_API_KEY not configured on the API).
                </div>
            )}

            {!loading && error && (
                <div style={{ color: "#EF4444", fontSize: 11, letterSpacing: 1 }}>
                    Narrative generation failed. The analysis data above is unaffected.
                </div>
            )}

            {!loading && narrative && (
                <div style={{ fontSize: 13, lineHeight: 1.6, color: "#FEF3C7" }}>
                    {narrative}
                </div>
            )}

            <div style={{
                marginTop: 12, fontSize: 9, letterSpacing: 1,
                color: "rgba(254,243,199,0.3)",
            }}>
                AI-generated commentary based on historical analog data. Not financial advice.
            </div>
        </div>
    );
}
